name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: silabs-internal
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: docker run zyclonite/sysbench cpu run
    - name: Run a multi-line scripts
      run: |
        ls
        pwd
        hostname
        cat /etc/os-release


